plugins {
    id 'com.android.application'
}

android {
    compileSdk 34
    namespace "top.youzix.nekoneko"

    defaultConfig {
        applicationId "top.youzix.nekoneko"
        minSdk 21
        targetSdk 33
        versionCode 36
        versionName "1.4.0"
    }

    signingConfigs {
        release {
            storeFile file("nekoneko.jks")
            storePassword "ADMIN.wxd1y12r"
            keyAlias "nekoneko"
            keyPassword "ADMIN.wxd1y12r"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
}
